
  
  
  <script>
  $( function() {
   
    var alltags = 
[
"IT",
"BPO",
"Sales",
"Application Programming",
"Marketing",
"Server Administrator",
"Accounting",
"Node Js",
"Angular",
"Healthcare",
"Fresher",
"Content Writing",
"Accounting",
"Advertising",
"Agriculture",
"Airline",
"Analytics",
"Animation",
"Application Programming",
"Architecture",
"Automation",
"Automobile",
"Automotive Jobs",
"Aviation",
"Bank",
"BPO",
"Brewery",
"Business Intelligence",
"Chemical",
"Client Server",
"Construction",
"Consultant",
"Consumer Durables",
"Content Writing",
"Corporate Planning",
"Customer Research",
"DBA",
"Defence",
"Digital Marketing",
"Affiliate Marketing",
"Animation",
"Article Writing",
"Content Marketing",
"Creative Writing",
"Email Marketing",
"Display Advertising",
"Ecommerce",
"EDP",
"Education Training",
"Electrician",
"Electronics",
"ERP",
"Big Data",
"Cloud Developer",
"SEO",
"SEO Writing",
"Social Media Marketing",
"Technical Writing",
"Translation",
"UX Design",
"VFX",
"Web Design",
"Software Developer",
"System Administrator",
"Sales Marketing",
"Sales Business Development",
"Delivery boy",
"Accountant",
"Back Office executive",
"Customer Care",
"Software Developer",
"Telesales",
"Telemarketing",
"Data Entry Operator",
"Human Resource",
"Banking",
"Customer service",
"Cashier",
"Construction",
"Driver",
"Data entry",
"Front desk receptionist",
"Graphic design",
"General manager",
"Graphic designer",
"Human resources",
"Healthcare administration",
"Information technology",
"Insurance",
"IT support",
"Internship",
"Interior designer",
"Journalism",
"Medical assistant",
"Manager",
"Manufacturing",
"Marketing",
"Medical office",
"Medical receptionist",
"Project manager",
"Receptionist",
"Teacher",
"JavaDeveloper",
"PHP Developer",
"Web developer",
"Ui Desiger",
"Android Developer",
"Business Development Associate",
"Business Development Executive",
"IOS Developer",
"Sap",
"Sap Abap",
"Sapient",
"Sap Basis",
"Sap Fico",
"Sap Sd",
"Sap Mm",
"Sap Labs India",
"Sap Bi",
"Sap Security",
"Pharma",
"Philips",
"Pharmacovigilance",
"Photoshop",
"Pharmacy",
"Photon Infotech",
"Photography",
"Pharma Marketing",
"Pharmaceutical",
"Back Office",
"Backend",
"Back Office Operations",
"Backup",
"Backend Operations",
"Background Verification",
"Backbone.js",
"Bacardi Martini",
"Sqls",
"SqlServer",
"SqlDba",
"SqlServer Dba",
"SqlStar International",
"SqlServer Development",
"SqlDevelopment",
"SqlDatabase",
"SqlServer Reporting Services",
"SqlQueries",
"Javas",
"Javascript",
"Javafx",
"JavaSwing",
"JavaArchitecture",
"JavaWeb Services",
"Javaji System Solutions",
"JavaApis",
"JavaServlets",
"JavaSecurity",
"Marketing",
"Market Research",
"Marketing",
"Marketing Management",
"Marketing Communication",
"Marks & Spencer",
"Marketing Executive",
"Marksans Pharma",
"Mark Exhaust Systems",
"Marketing Research",
"Digital Marketing",
"Pega",
"ERP",
"PHP",
"Java Developer",
"Fresher",
"Project coordinator",
"Office Boy",
"CS",
"Accountants",
"Clerks",
"Engineers",
"Medical officers",
"IPS officer",
"Nurse",
"Civil services",
"SSC",
"State Public Service Commision",
"Airforce",
"Railway Job",
"Gate Job",
"Banking Job",
"AIIMS Jobs",
"Defence Job",
"CA",
"CS",
"Graphic Designer",
"Sales Marketing",
"Student",
"Internship",
"Fresher",
"HR Fresher",
"HR Manager",
"HR Excecutive Fresher",
"SEO Fresher",
"Telecallers",
"PHP Fresher",
"Andriod Ffresher",
"BDE Fresher",
"Marketing",
"Operations",
"Designer",
"Web development",
"Content Writing",
"PR",
"HR",
"Finance",
"Finance Fresher",
"MBA Finance",
"MCA",
"MBA",
"BBA",
"BCA",
"BCOM",
"BTECH",
"Data Entry",
"Work from Home",
"Jobs",
"Cyber Security",
"BDE",
"Bussiness Development Interns",
"IT student",
"Non IT student",
"HR internship",
"Equity Research",
"Credit Risk",
"Working Capital",
"Marketing",
"Social Media",
"Marketing Strategy",
"HR Analytics",
"Calling",
"BPO",
"Entry",
"Oracle",
"PLSQL Developer",
"HR",
"Andriod",
"Java",
"Typing",
"Work from home",
"data entry",
"php",
"account"













];


    $( "#alltags" ).autocomplete({
      source: alltags
    });

     $( ".alltags" ).autocomplete({
      source: alltags
    });
  } );
  </script>