
  <script>
  $( function() {
   
    var qualification = 
[
"10+2 or Below  ",
"Arts and Humanities  ",
"Commerce  ",
"Other  ",
"Science  ",
"B.A  ",
"Arts and Humanities  ",
"Other  ",
"Communication  ",
"Economics  ",
"English  ",
"Fine Arts  ",
"Geography  ",
"Hindi  ",
"History  ",
"Maths  ",
"Philosophy  ",
"Political Science  ",
"PR\/Advertising  ",
"Psychology  ",
"Sanskrit  ",
"Sociology  ",
"Visual Arts  ",
"Graphics \/ Web designing  ",
"Journalism \/ Mass Communication  ",
"B.Arch  ",
"Architecture  ",
"B.B.A \/ B.M.S  ",
"Management  ",
"Other  ",
"Finance \/ Accounting  ",
"Marketing  ",
"B.C.A  ",
"Computers  ",
"B.Com  ",
"Commerce  ",
"B.Ed  ",
"Education  ",
"B.Pharma  ",
"Pharmacy  ",
"B.Sc  ",
"Computers  ",
"Other  ",
"Maths  ",
"Agriculture  ",
"Anthropology  ",
"Biochemistry  ",
"Biology  ",
"Biomedical  ",
"Botany  ",
"Chemistry  ",
"Food Technology  ",
"Geology  ",
"Home Science  ",
"Microbiology  ",
"Physics  ",
"Statistics  ",
"Zoology  ",
"Electronics\/Telecommunication  ",
"B.Tech\/B.E  ",
"Computers  ",
"Architecture  ",
"Agriculture  ",
"Biochemistry  ",
"Biomedical  ",
"Aeronautics  ",
"Automobile  ",
"Biotechnology  ",
"Chemical  ",
"Civil  ",
"Electrical  ",
"Electronics\/Telecommunication  ",
"Energy  ",
"Environmental  ",
"Instrumentation  ",
"IT-Software  ",
"Marine  ",
"Mechanical  ",
"Metallurgy  ",
"Mineral  ",
"Mining  ",
"Nuclear  ",
"Other Engineering  ",
"Production\/Industrial  ",
"Textile  ",
"BDS  ",
"Dentistry  ",
"BHM  ",
"Hotel Management  ",
"BVSC  ",
"Veterinary Science  ",
"C.A  ",
"Chartered Accountant  ",
"C.F.A  ",
"Chartered Financial Analyst  ",
"C.S  ",
"Company Secretary  ",
"Diploma  ",
"Arts and Humanities  ",
"Commerce  ",
"Computers  ",
"Management  ",
"Other  ",
"Science  ",
"Maths  ",
"Visual Arts  ",
"Finance \/ Accounting  ",
"Marketing  ",
"Pharmacy  ",
"Chemical  ",
"Civil  ",
"Electrical  ",
"Electronics\/Telecommunication  ",
"Mechanical  ",
"Other Engineering  ",
"Dentistry  ",
"Hotel Management  ",
"Anaesthesiology  ",
"Cardiology  ",
"Fashion Designing  ",
"General Surgery  ",
"Graphics \/ Web designing  ",
"Insurance  ",
"Neurology  ",
"Nursing  ",
"Nutrition & Dietetics  ",
"Obstetrics & Gynaecology  ",
"Ophthalmology  ",
"Orthopaedics  ",
"Other Medicine  ",
"Pathology  ",
"Physiotherapy  ",
"Psychiatry  ",
"Radiology  ",
"Tourism  ",
"Vocational Course  ",
"Dermatology,Venereology & Leprosy  ",
"Pediatrics  ",
"ICWA \/ CMA  ",
"Cost Accountant  ",
"Integrated PG  ",
"Management  ",
"Other  ",
"PR\/Advertising  ",
"Tourism  ",
"Journalism \/ Mass Communication  ",
"LL.M  ",
"Law  ",
"LLB  ",
"Law  ",
"M.A  ",
"Arts and Humanities  ",
"Other  ",
"Communication  ",
"Economics  ",
"English  ",
"Fine Arts  ",
"Geography  ",
"Hindi  ",
"History  ",
"Maths  ",
"Philosophy  ",
"Political Science  ",
"PR\/Advertising  ",
"Psychology  ",
"Sanskrit  ",
"Sociology  ",
"Visual Arts  ",
"Graphics \/ Web designing  ",
"Journalism \/ Mass Communication  ",
"M.C.A  ",
"Computers  ",
"M.Com  ",
"Commerce  ",
"M.Ed  ",
"Education  ",
"M.Pharma  ",
"Pharmacy  ",
"M.Sc  ",
"Computers  ",
"Other  ",
"Maths  ",
"Agriculture  ",
"Anthropology  ",
"Biochemistry  ",
"Biology  ",
"Biomedical  ",
"Botany  ",
"Chemistry  ",
"Food Technology  ",
"Geology  ",
"Home Science  ",
"Microbiology  ",
"Physics  ",
"Statistics  ",
"Zoology  ",
"Electronics\/Telecommunication  ",
"M.Tech  ",
"Computers  ",
"Architecture  ",
"Agriculture  ",
"Biochemistry  ",
"Biomedical  ",
"Aeronautics  ",
"Automobile  ",
"Biotechnology  ",
"Chemical  ",
"Civil  ",
"Electrical  ",
"Electronics\/Telecommunication  ",
"Energy  ",
"Environmental  ",
"Instrumentation  ",
"IT-Software  ",
"Marine  ",
"Mechanical  ",
"Metallurgy  ",
"Mineral  ",
"Mining  ",
"Nuclear  ",
"Other Engineering  ",
"Production\/Industrial  ",
"Textile  ",
"Aviation  ",
"MBA\/PGDM  ",
"Finance \/ Accounting  ",
"Marketing  ",
"Advertising\/Mass Communication  ",
"HR\/ Industrial Relations  ",
"Information Technology  ",
"International Business  ",
"Operations  ",
"Other Management  ",
"MBBS  ",
"Medicine and Health Sciences  ",
"MD\/MS  ",
"Other  ",
"Pharmacy  ",
"Biochemistry  ",
"Microbiology  ",
"Anaesthesiology  ",
"Cardiology  ",
"General Surgery  ",
"Neurology  ",
"Obstetrics & Gynaecology  ",
"Ophthalmology  ",
"Orthopaedics  ",
"Pathology  ",
"Psychiatry  ",
"Radiology  ",
"Anatomy  ",
"Dermatology,Venereology & Leprosy  ",
"ENT  ",
"Forensic Medicine  ",
"General Medicine  ",
"Hospital Administration  ",
"Lab Medicine  ",
"Pediatrics  ",
"Physiology  ",
"MDS  ",
"Dentistry  ",
"MMH  ",
"Hotel Management  ",
"MPHIL  ",
"Philosophy  ",
"MVSC  ",
"Veterinary Science  ",
"Other  ",
"Other  ",
"PG Diploma  ",
"Arts and Humanities  ",
"Commerce  ",
"Computers  ",
"Management  ",
"Other  ",
"Science  ",
"Maths  ",
"Visual Arts  ",
"Finance \/ Accounting  ",
"Marketing  ",
"Chemical  ",
"Civil  ",
"Electrical  ",
"Electronics\/Telecommunication  ",
"Mechanical  ",
"Hotel Management  ",
"Anaesthesiology  ",
"Cardiology  ",
"Fashion Designing  ",
"General Surgery  ",
"Graphics \/ Web designing  ",
"Insurance  ",
"Neurology  ",
"Nursing  ",
"Nutrition & Dietetics  ",
"Obstetrics & Gynaecology  ",
"Ophthalmology  ",
"Orthopaedics  ",
"Other Medicine  ",
"Pathology  ",
"Physiotherapy  ",
"Psychiatry  ",
"Radiology  ",
"Tourism  ",
"Vocational Course  ",
"Dermatology,Venereology & Leprosy  ",
"Pediatrics  ",
"Ph.D\/Doctorate  ",
"Arts and Humanities  ",
"Commerce  ",
"Computers  ",
"Other  ",
"Science  ",
"Communication  ",
"Economics  ",
"Fine Arts  ",
"History  ",
"Maths  ",
"Philosophy  ",
"Sociology  ",
"Visual Arts  ",
"Architecture  ",
"Finance \/ Accounting  ",
"Marketing  ",
"Pharmacy  ",
"Agriculture  ",
"Biochemistry  ",
"Biology  ",
"Biomedical  ",
"Chemistry  ",
"Food Technology  ",
"Microbiology  ",
"Physics  ",
"Statistics  ",
"Automobile  ",
"Biotechnology  ",
"Chemical  ",
"Civil  ",
"Electrical  ",
"Energy  ",
"Environmental  ",
"Instrumentation  ",
"Mechanical  ",
"Nuclear  ",
"Other Engineering  ",
"Production\/Industrial  ",
"Hotel Management  ",
"Fashion Designing  ",
"Journalism \/ Mass Communication  ",
"Law  ",
"Aviation  ",
"Advertising\/Mass Communication  ",
"HR\/ Industrial Relations  ",
"International Business  ",
"Other Management  ",
"Dermatology,Venereology & Leprosy  ",
"Ceramics  ",
"Literature  ",
"Medicine and Health Sciences  ",
"Other Arts  "
];


    $( "#qualification" ).autocomplete({
      source: qualification
    });

     $( ".qualification" ).autocomplete({
      source: qualification
    });
  } );
  </script>